INTERNSHIP-207 openapi client + user account registration/activation
uclouvain/osis-portal-internship pull request #39
Opened 2021-01-13 15:51 UTC by mathieuzen

Référence Jira : INTERNSHIP-207

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-01-14 14:12 UTC, lspitaels requested changes

2021-01-14 14:12 UTC, lspitaels commented on views/api_client.py
> +from django.conf import settings
Manque la licence

2021-01-14 16:23 UTC, mathieuzen commented on templates/internship_authentication/login.html
> +                                    -->
Oui je me suis dit que j'allais peut-être en avoir besoin mais je peux l'enlever en fait

2021-01-15 12:11 UTC, lspitaels requested changes

2021-01-15 12:11 UTC, lspitaels commented on requirements.txt
> +Pillow==6.2.2
Pourquoi le retour à une version plus ancienne?

2021-01-15 12:11 UTC, lspitaels commented on requirements.txt
> +coverage==4.5.1
Pourquoi le retour à une version plus ancienne?

2021-01-15 12:11 UTC, lspitaels commented on templates/internship_django_registration/registration_form.html
> +                password2.setCustomValidity("{% trans "The two password fields didn't match." %}");
je dirais "doesn't"

2021-01-15 12:11 UTC, lspitaels commented on templates/internship_django_registration/registration_form.html
> +                password2.setCustomValidity("{% trans "The two password fields didn't match." %}");
et il manque la traduction

2021-01-15 13:01 UTC, mathieuzen commented on requirements.txt
> +Pillow==6.2.2
c'est celle de osis-portal, je préfère aligner le module à son parent

2021-01-15 13:01 UTC, mathieuzen commented on requirements.txt
> +coverage==4.5.1
idem

2021-01-15 13:03 UTC, mathieuzen commented on templates/internship_django_registration/registration_form.html
> +                password2.setCustomValidity("{% trans "The two password fields didn't match." %}");
c'est le texte de django-registration quand il fait la validation du post

2021-01-15 13:05 UTC, mathieuzen commented on templates/internship_django_registration/registration_form.html
> +                password2.setCustomValidity("{% trans "The two password fields didn't match." %}");
et la traduction et dans la lib

2021-01-15 13:09 UTC, lspitaels approved these changes

2021-01-15 13:52 UTC, merged