INTERNSHIP-198 create view with template for score encoding sheet
uclouvain/osis-portal-internship pull request #40
Opened 2021-01-15 16:29 UTC by mathieuzen

Référence Jira : INTERNSHIP-198

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-01-25 15:26 UTC, BenJneB requested changes

2021-01-25 15:26 UTC, BenJneB commented on locale/fr_BE/LC_MESSAGES/django.po
> +msgstr "L'accès aux stages est seulement autorisées aux étudiants-stagiaires et aux maîtres de stage"
autorisés*

2021-01-25 15:26 UTC, BenJneB commented on locale/fr_BE/LC_MESSAGES/django.po
> +msgstr "Veuillez contacter l'administration des stages pour obtenir un compte utilisateur"
remet le (STAC) peut être ?

2021-01-25 15:26 UTC, BenJneB commented on locale/fr_BE/LC_MESSAGES/django.po
> +msgstr "Quel(s) méthode(s) d'apprentissage suggérez-vous pour s'améliorer ?"
Quelle(s)

2021-01-25 15:26 UTC, BenJneB commented on locale/fr_BE/LC_MESSAGES/django.po
> +"Votre compte utilisateur est maintenant actif. Vous pouvez vous connceter "
connecter

2021-01-25 15:26 UTC, BenJneB commented on requirements.txt
> +--extra-index-url https://uclouvain.github.io/osis-internship-sdk/
juste m'expliquer pour que je sache :D

2021-01-25 15:26 UTC, BenJneB commented on templates/internship_score_encoding.html
> +                      <p>2/12 {% trans 'encoded grade(s)' %}</p>
2/12 ?

2021-01-25 15:26 UTC, BenJneB commented on templates/internship_score_encoding_sheet.html
> +    console.log( document.querySelector('#period-select'));
a virer

2021-01-25 15:26 UTC, BenJneB commented on templates/internship_score_encoding_sheet.html
> +            console.log('select');
idem

2021-01-25 15:57 UTC, mathieuzen commented on requirements.txt
> +--extra-index-url https://uclouvain.github.io/osis-internship-sdk/
en fait j'ai ajouté le repo en requirement mais je voulais faire en sorte que ce soit mis à jour facilement en notifiant la mise à jour, il y a quelque chose à faire avec les index fourni sur une page séparée mais j'y suis pas encore arrivé 
(pour le moment ça sert juste description cette page)

2021-01-27 13:20 UTC, BenJneB approved these changes

2021-01-27 13:22 UTC, merged