INTERNSHIP-217 arrange urls and views to dissociate students and masters
uclouvain/osis-portal-internship pull request #41
Opened 2021-01-27 15:12 UTC by mathieuzen

Référence Jira : INTERNSHIP-217

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-01-27 15:29 UTC, BenJneB requested changes

2021-01-27 15:29 UTC, BenJneB commented on views/main.py
> +    else:
tu peux virer le else du coup?

2021-01-28 08:14 UTC, mathieuzen commented on views/main.py
> +    else:
bah non pas vraiment si pas étudiant et pas master, on revient à la page d'accueil d'osis-portal

2021-01-28 10:20 UTC, BenJneB commented on views/main.py
> +    else:
non juste le 'else:'
il passera doffice sous le elif sans besoin d'ajouter le else

2021-01-28 10:21 UTC, BenJneB commented on views/main.py
> +    else:
```python3
if a:
   return
elif b:
   return
return
```

2021-01-28 10:53 UTC, mathieuzen commented on views/main.py
> +    else:
ah ok oui ça marche je fais ça merci

2021-01-28 13:50 UTC, merged